package Vista;
import Controlador.CtrlEquipos;
import Modelo.ClsClientes;
import Modelo.ClsEquipos;
//import Modelo.ClsTipoTrabajador;
import Modelo.QueryClientes;
import Modelo.QueryEquipos;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import javax.swing.text.JTextComponent;
public class FrmNewCliente extends javax.swing.JFrame {
    /**
     * Creates new form FrmUsuarios
     */
    public FrmNewCliente() {
        initComponents();
////// Implementar el código para el Combo Necesario
    boxNombre.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
    @Override
        public void keyReleased(KeyEvent evt) {
        // Instanciar la Clase para crear un objeto y usar los metodos
            QueryClientes modelo = new QueryClientes();
            String cadenaEscrita = boxNombre.getEditor().getItem().toString().toUpperCase().trim();                
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                buscar(cadenaEscrita);
                boxNombre.setEnabled(false);
                btnGuardar.setVisible(true);
            }
            if (evt.getKeyCode() >= 65 && evt.getKeyCode() <= 90 || evt.getKeyCode() >= 97 && evt.getKeyCode() <= 122 || evt.getKeyCode() == 8) {
                boxNombre.setModel(modelo.getLista(cadenaEscrita));
                if (boxNombre.getItemCount() > 0) {
                    boxNombre.showPopup();       
                    if(evt.getKeyCode()!=8) {
                        ((JTextComponent)boxNombre.getEditor().getEditorComponent()).select(cadenaEscrita.length(),boxNombre.getEditor().getItem().toString().length());
                    } else {
                        boxNombre.getEditor().setItem(cadenaEscrita);
                        }
                } else {
                    boxNombre.addItem(cadenaEscrita);
                }
            }
        }
    });
//////////////////  Fin de implementación del combo
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnDetEditar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        boxNombre = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtClienteCod = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContenido = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();
        btnDetNuevo = new javax.swing.JButton();
        btnDetEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        jLabel1.setText("Mantenimiento de Clientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel4.setText("CODIGO  : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 90, 20));

        jLabel5.setText("CORREO ELECTRONICO : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 160, 20));

        btnDetEditar.setText("Modificar");
        getContentPane().add(btnDetEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 80, 30));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 80, 80));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel7.setText("APELLIDOS Y NOMBRES : ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 160, -1));

        jLabel10.setText("TELEFONO : ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 90, 20));

        boxNombre.setEditable(true);
        boxNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                boxNombreFocusLost(evt);
            }
        });
        boxNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                boxNombreKeyTyped(evt);
            }
        });
        getContentPane().add(boxNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 500, -1));

        jLabel3.setText("DIRECCION : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 90, -1));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 500, -1));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 240, -1));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 500, -1));
        getContentPane().add(txtClienteCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 230, -1));

        tblContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblContenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContenidoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblContenido);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 670, 190));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("EQUIPOS DISPONIBLES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 320, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 650, 10));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 80, 30));

        btnDetNuevo.setText("Nuevo");
        btnDetNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDetNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 80, 30));

        btnDetEliminar.setText("Eliminar");
        getContentPane().add(btnDetEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 80, 30));

        setSize(new java.awt.Dimension(733, 647));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void buscar(String nombre) {
        QueryClientes modelo = new QueryClientes();
//        JOptionPane.showMessageDialog(null,"Nro Documento "+nombre.trim());
        String datos[] = modelo.buscar(nombre);
        if (datos[0] != null) {
            txtId.setText(datos[0]);  // encuentra y pasa el id al txtIDPer
        //    JOptionPane.showMessageDialog(null,"Nro Documento "+datos[0]);
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se encontro registro !!!", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }
    private boolean comparar(String cadena){
    Object [] lista=boxNombre.getComponents();
    boolean encontrado=false;
        for (Object object : lista) {
            JOptionPane.showMessageDialog(null,"cadena =====  "+ object + "  Cadena  : "+cadena);
            if(cadena.equals(object)){
                encontrado=true;
              break;
            }
        }
       return encontrado;
    }     
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        FrmMantClientes frm = new FrmMantClientes();
        frm.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnSalirActionPerformed

    private void boxNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxNombreKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_boxNombreKeyTyped

    private void boxNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_boxNombreFocusLost
        // TODO add your handling code here:
//         JOptionPane.showMessageDialog(null,"texto a buscar  "+boxNombre.getSelectedItem().toString());
//        buscar(boxNombre.getSelectedItem().toString());
    }//GEN-LAST:event_boxNombreFocusLost

    private void tblContenidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContenidoMouseClicked
        // TODO add your handling code here:
/*        if(this.tblContenido.getSelectedRow()!=-1){
            QueryPersonas modelo = new QueryPersonas();//clase donde estan los querys
            ClsPersonas persona = new ClsPersonas();
            this.txtId.setText(tblContenido.getValueAt(tblContenido.getSelectedRow(), 6).toString());
            int c=Integer.parseInt(this.txtId.getText());
            persona=modelo.devuelvePersona(c);
            this.txtApePat.setText(persona.getAp_paterno());
            this.txtApeMat.setText(persona.getAp_materno());
            this.txtNombres.setText(persona.getNombres());
            this.txtNro_doc.setText(persona.getNro_documento());
            this.txtTipo.setText(String.valueOf(persona.getTipo_per()));
            this.txtSexo.setText(String.valueOf(persona.getSexo()));
            if(persona.getSexo()==1){
                this.cmbTipo.setSelectedItem("Masculino");
            }else {
                this.cmbTipo.setSelectedItem("Femenino");
            }
            if(persona.getTipo_per()==1){
                this.cmbTipo.setSelectedItem("Persona Natural");
            }else {
                this.cmbTipo.setSelectedItem("Persona Juridica");
            }
            //Poner fecha a JdateChooser
            SimpleDateFormat formatoDelTexto = new SimpleDateFormat("yyyy-MM-dd");
            String strFecha = persona.getFecha_nac();
            Date fecha = null;
            try {
                fecha = formatoDelTexto.parse(strFecha);
                this.jDateFecNacimiento.setDate(fecha);
            } catch (ParseException ex) {
                //JOptionPane.showMessageDialog(null, ex.getMessage());
                System.out.println(this.jDateFecNacimiento.getDate().toString());
            }
            this.btnDetModificar.setEnabled(false);
//            this.btnModificar.setEnabled(true);
//            this.btnEliminar.setEnabled(true);
            this.btnBuscar.doClick();
        } */
    }//GEN-LAST:event_tblContenidoMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnDetNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetNuevoActionPerformed
        // TODO add your handling code here:
// Cargar formulario para ingreso de nuevo equipo
        ClsEquipos mod = new ClsEquipos();
        QueryEquipos modQ = new QueryEquipos();
        FrmEquipos frm = new FrmEquipos();
        CtrlEquipos ctrl = new CtrlEquipos(mod,modQ,frm);
        ctrl.iniciar();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDetNuevoActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNewCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> boxNombre;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnDetEditar;
    public javax.swing.JButton btnDetEliminar;
    public javax.swing.JButton btnDetNuevo;
    public javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable tblContenido;
    public javax.swing.JTextField txtClienteCod;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
