package Vista;
import Modelo.ClsPersonas;
import Modelo.QueryPersonas;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
public class FrmPersonas extends javax.swing.JFrame {
    /**
     * Creates new form FrmUsuarios
     */
    public FrmPersonas() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtApePat = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContenido = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNro_doc = new javax.swing.JTextField();
        txtApeMat = new javax.swing.JTextField();
        jDateFecNacimiento = new com.toedter.calendar.JDateChooser();
        txtTipo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        jLabel1.setText("Mantenimiento de Personas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));

        jLabel2.setText("APELLIDO MATERNO : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 130, -1));

        jLabel4.setText("FECHA NACIMIENTO : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 130, 20));

        btnGuardar.setText("Guardar");
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, 80, -1));

        btnEliminar.setText("Eliminar");
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 80, -1));

        btnModificar.setText("Modificar");
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, 80, -1));

        btnLimpiar.setText("Limpiar");
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 80, -1));

        txtApePat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApePatFocusLost(evt);
            }
        });
        txtApePat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApePatActionPerformed(evt);
            }
        });
        getContentPane().add(txtApePat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 310, -1));
        getContentPane().add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 60, -1));

        txtNombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombresFocusLost(evt);
            }
        });
        getContentPane().add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 310, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 870, 10));

        jLabel6.setText("BUSCAR : ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, 20));

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 520, -1));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 80, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 80, -1));

        tblContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblContenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContenidoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblContenido);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 890, 240));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persona Natural", "Persona Juridica" }));
        cmbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoItemStateChanged(evt);
            }
        });
        cmbTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbTipoFocusLost(evt);
            }
        });
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 150, 30));

        jLabel7.setText("APELLIDO PATERNO : ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 130, -1));

        jLabel8.setText("SEXO : ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 70, -1));
        getContentPane().add(txtNro_doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 190, -1));

        txtApeMat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApeMatFocusLost(evt);
            }
        });
        getContentPane().add(txtApeMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 350, -1));

        jDateFecNacimiento.setDateFormatString("dd/MM/yyyy");
        jDateFecNacimiento.setPreferredSize(new java.awt.Dimension(50, 20));
        getContentPane().add(jDateFecNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 200, 30));
        getContentPane().add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 60, -1));

        jLabel10.setText("NOMBRES : ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 70, -1));

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        cmbSexo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSexoItemStateChanged(evt);
            }
        });
        cmbSexo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbSexoFocusLost(evt);
            }
        });
        cmbSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSexoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 170, 30));

        jLabel9.setText("Nro. D.N.I. : ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 70, -1));

        setSize(new java.awt.Dimension(942, 531));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // para cuando se tipea genera el boton buscar
            QueryPersonas modelo = new QueryPersonas();//clase donde estan los querys
            this.tblContenido.setEnabled(true);  // habilitar tabla
            tblContenido.setModel(modelo.listar(txtBuscar.getText().toUpperCase()));
            // Establece el ancho de las columnas
            TableColumnModel columnModel = tblContenido.getColumnModel();
                columnModel.getColumn(0).setPreferredWidth(40);
                columnModel.getColumn(1).setPreferredWidth(160);
                columnModel.getColumn(2).setPreferredWidth(160);
                columnModel.getColumn(3).setPreferredWidth(160);
                columnModel.getColumn(4).setPreferredWidth(100);
                columnModel.getColumn(5).setPreferredWidth(100);
                columnModel.getColumn(6).setPreferredWidth(50);
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        FrmPrincipal frm = new FrmPrincipal();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tblContenidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContenidoMouseClicked
        // TODO add your handling code here:
        if(this.tblContenido.getSelectedRow()!=-1){            
            QueryPersonas modelo = new QueryPersonas();//clase donde estan los querys
            ClsPersonas persona = new ClsPersonas();
            this.txtId.setText(tblContenido.getValueAt(tblContenido.getSelectedRow(), 6).toString()); 
            int c=Integer.parseInt(this.txtId.getText());            
            persona=modelo.devuelvePersona(c);
            this.txtApePat.setText(persona.getAp_paterno()); 
            this.txtApeMat.setText(persona.getAp_materno()); 
            this.txtNombres.setText(persona.getNombres()); 
            this.txtNro_doc.setText(persona.getNro_documento()); 
            this.txtTipo.setText(String.valueOf(persona.getTipo_per()));
            this.txtSexo.setText(String.valueOf(persona.getSexo()));
            if(persona.getSexo()==1){
                this.cmbTipo.setSelectedItem("Masculino");
            }else {
                this.cmbTipo.setSelectedItem("Femenino");
            }
            if(persona.getTipo_per()==1){
                this.cmbTipo.setSelectedItem("Persona Natural");
            }else {
                this.cmbTipo.setSelectedItem("Persona Juridica");
            }
            //Poner fecha a JdateChooser 
            SimpleDateFormat formatoDelTexto = new SimpleDateFormat("yyyy-MM-dd");
            String strFecha = persona.getFecha_nac();
            Date fecha = null;
            try {
                fecha = formatoDelTexto.parse(strFecha);
                this.jDateFecNacimiento.setDate(fecha);
            } catch (ParseException ex) {
                //JOptionPane.showMessageDialog(null, ex.getMessage());
                 System.out.println(this.jDateFecNacimiento.getDate().toString());
            }          
            this.btnGuardar.setEnabled(false);
            this.btnModificar.setEnabled(true);
            this.btnEliminar.setEnabled(true);        
            this.btnBuscar.doClick();
        }    
    }//GEN-LAST:event_tblContenidoMouseClicked
    private void txtApePatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApePatFocusLost
        // TODO add your handling code here:
        this.txtApePat.setText(this.txtApePat.getText().toUpperCase());
    }//GEN-LAST:event_txtApePatFocusLost
    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed
    private void txtApePatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApePatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApePatActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // TODO add your handling code here:
        this.txtBuscar.setText(this.txtBuscar.getText().toUpperCase());
    }//GEN-LAST:event_txtBuscarKeyPressed
    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:     
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void cmbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoItemStateChanged
        // TODO add your handling code here:
    //    ClsTipodoc tipo=(ClsTipodoc) this.cmbTipo.getSelectedItem();
    //    int id = tipo.getUsutipid();
    //    this.txtId.setText(Integer.toString(id));                
    }//GEN-LAST:event_cmbTipoItemStateChanged

    private void cmbTipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbTipoFocusLost
        // TODO add your handling code here:
        String varEstado = this.cmbTipo.getSelectedItem().toString();
        if(varEstado=="Masculino") {
            this.txtSexo.setText("1");                
        } else {
            this.txtSexo.setText("0");                
        }
    }//GEN-LAST:event_cmbTipoFocusLost

    private void txtApeMatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApeMatFocusLost
        // TODO add your handling code here:
        this.txtApeMat.setText(this.txtApeMat.getText().toUpperCase());
    }//GEN-LAST:event_txtApeMatFocusLost

    private void txtNombresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombresFocusLost
        // TODO add your handling code here:
        this.txtNombres.setText(this.txtNombres.getText().toUpperCase());
    }//GEN-LAST:event_txtNombresFocusLost

    private void cmbSexoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSexoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSexoItemStateChanged

    private void cmbSexoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbSexoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSexoFocusLost

    private void cmbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSexoActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPersonas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    public javax.swing.JComboBox<Object> cmbSexo;
    public javax.swing.JComboBox<Object> cmbTipo;
    public com.toedter.calendar.JDateChooser jDateFecNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable tblContenido;
    public javax.swing.JTextField txtApeMat;
    public javax.swing.JTextField txtApePat;
    private javax.swing.JTextField txtBuscar;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtNombres;
    public javax.swing.JTextField txtNro_doc;
    public javax.swing.JTextField txtSexo;
    public javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
