package CrudCategoria;
//import Modelo.ClsTipoTrabajador;

import MantProductos.FrmGProductos;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


// importamos la variable con el id del cliente
public class FrmListaCategoria extends javax.swing.JFrame {
    
    CtrlCategoria controlador;

    public FrmListaCategoria() {
        initComponents();
        controlador = new CtrlCategoria(this);
        preTabla();
    }
    
    public void preTabla(){
        QueryCategoria prueba= new QueryCategoria();
        ArrayList <ClsCategoria> categorias = prueba.marcasArr();
        initTabla(categorias);
    }
    
    public void initTabla(ArrayList <ClsCategoria> m){        
        String[] columnNames = {"Nro.","Codigo","Nombre de la categoria",};
        DefaultTableModel modelo = new DefaultTableModel(null,columnNames);       
        jTable1.setModel(modelo);
        
        for(int  i=0; i<m.size();i++){
            String[] fila={Integer.toString(i+1),Integer.toString(m.get(i).getCodCateg()),m.get(i).getNomCateg()};
            modelo.addRow(fila);
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        btnCategoriaAdd = new javax.swing.JButton();
        btnCategoriaMod = new javax.swing.JButton();
        btnCategoriaDel = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CATEGORIA - PRODUCTOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        btnSalir.setText("Buscar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BUSCAR:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 70, -1));

        jTextField1.setForeground(new java.awt.Color(0, 51, 204));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 470, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 710, 340));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 60, -1));

        btnCategoriaAdd.setBackground(new java.awt.Color(50, 216, 193));
        btnCategoriaAdd.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btnCategoriaAdd.setForeground(new java.awt.Color(0, 102, 205));
        btnCategoriaAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add32.png"))); // NOI18N
        btnCategoriaAdd.setText("Nueva Categoria");
        btnCategoriaAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCategoriaAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnCategoriaAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, 170, -1));

        btnCategoriaMod.setBackground(new java.awt.Color(50, 216, 193));
        btnCategoriaMod.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btnCategoriaMod.setForeground(new java.awt.Color(0, 102, 205));
        btnCategoriaMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit32.png"))); // NOI18N
        btnCategoriaMod.setText("Editar");
        btnCategoriaMod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCategoriaMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaModActionPerformed(evt);
            }
        });
        getContentPane().add(btnCategoriaMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 170, -1));

        btnCategoriaDel.setBackground(new java.awt.Color(50, 216, 193));
        btnCategoriaDel.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btnCategoriaDel.setForeground(new java.awt.Color(0, 102, 205));
        btnCategoriaDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        btnCategoriaDel.setText("Eliminar");
        btnCategoriaDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCategoriaDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaDelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCategoriaDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 170, -1));

        btnSalir1.setBackground(new java.awt.Color(0, 204, 153));
        btnSalir1.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btnSalir1.setForeground(new java.awt.Color(0, 102, 205));
        btnSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir4.png"))); // NOI18N
        btnSalir1.setText("Salir");
        btnSalir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inventario.jpg"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-880, -290, -1, -1));

        setSize(new java.awt.Dimension(938, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    //Actualizar
    private void btnCategoriaModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaModActionPerformed
        
    }//GEN-LAST:event_btnCategoriaModActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        FrmGProductos frm = new FrmGProductos();
        frm.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnSalir1ActionPerformed

    //Metodooo para añadir
    private void btnCategoriaAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaAddActionPerformed

    }//GEN-LAST:event_btnCategoriaAddActionPerformed

    
    //Eliminar
    private void btnCategoriaDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaDelActionPerformed
 
    }//GEN-LAST:event_btnCategoriaDelActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmListaCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCategoriaAdd;
    public javax.swing.JButton btnCategoriaDel;
    public javax.swing.JButton btnCategoriaMod;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnSalir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
