package Arranque;
import Login.CtrlLogin;
import Login.ClsUsuarios;
import Login.QueryUsuarios;
import Login.FrmLogin;
import com.sun.awt.AWTUtilities;
import java.awt.Color;
import javax.swing.UIManager;


/**
 *
 * @author 
 */
public class Inicio extends javax.swing.JFrame {
    public Inicio() {
        initComponents();
        AWTUtilities.setWindowOpaque(this, false);
        // Cambiar Color a barra
        UIManager.put( "nimbusOrange", new Color( 235, 32, 18 ) );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barra = new javax.swing.JProgressBar();
        lblPorcentaje = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setUndecorated(true);
        getContentPane().setLayout(null);

        barra.setForeground(new java.awt.Color(235, 32, 18));
        getContentPane().add(barra);
        barra.setBounds(60, 280, 310, 14);

        lblPorcentaje.setForeground(new java.awt.Color(255, 255, 255));
        lblPorcentaje.setText("0 %");
        getContentPane().add(lblPorcentaje);
        lblPorcentaje.setBounds(190, 260, 40, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/superpinguinos3.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-110, 0, 510, 300);

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Inicio frmP = new Inicio(); 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmP.setVisible(true);
            }
        });
                try {
            for(int i=0;i<=100;i++) {
                Thread.sleep(20);
                frmP.barra.setValue(i);
                frmP.lblPorcentaje.setText(Integer.toString(i)+" %");
            }
        } catch(Exception e) {            
        }
        ClsUsuarios mod = new ClsUsuarios();
        QueryUsuarios modQ = new QueryUsuarios();
        FrmLogin frm = new FrmLogin();
        
        CtrlLogin ctrl = new CtrlLogin(mod,modQ,frm);
        ctrl.iniciar();
        frm.setVisible(true);
        frmP.dispose();                
                
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblPorcentaje;
    // End of variables declaration//GEN-END:variables
}
